### ISSUE TITLE
Updating legacy code 

### ISSUE THREAD

**Issue by rizzla22** [alexedwards/scs#102]
I running into a number of problems with methods not being found or instantiated but cant find any documentation on how to resolve or what the updates where. these are just a sample, have you any tips ?

`var  session *scs.Manager`
Throws error: `Manager not declared by package scs`

`session = scs.NewCookieManager("demo")`
Throws error: `NewCookieManager not declared by package scs`

`var session, _ = sessionStore.Load(r.Request)`
Throws error: `cannot use r.Request (variable of type *http.Request) as context.Context value in argument to sessionStore.Load: missing method Deadline`

**Comment by TheWashiba** [comment]
I think this can be closed @alexedwards
