### ISSUE TITLE
Can't find BuntDB store

### ISSUE THREAD

**Issue by gandaldf** [alexedwards/scs#116]
Hi, I would like to user the BuntDB store but I can't find it... I searched in the old issues and I found that #13 added that exact feature but now it seems disappeard from the master branch.
Can you help me with this?

**Comment by alexedwards** [comment]
The code for the old buntstore implementation is here: https://github.com/alexedwards/scs/tree/v1.4.1/stores/buntstore

I can't remember why this didn't get included as part of the v2 release. It may simply have been that I was short on time and planned to do it later, but didn't get around to it.

If you would like to create a PR to add it back in I'd be happy to accept it. It would be good to include go.mod and go.sum files too referencing the latest BuntDB version (v1.2.6 based on a quick check).

**Comment by gandaldf** [comment]
Ok! I'll find some time to submit a PR.
Thank you!
