### ISSUE TITLE
Gin middleware

### ISSUE THREAD

**Issue by gandaldf** [alexedwards/scs#118]
Hi! Is there a way to get SCS working with Gin?
I didn't find any middleware or example, could anyone please help me to find out a way?

**Comment by alexedwards** [comment]
I'm afraid that I never use Gin, so I don't have any experience here. 

Did you get it working?

**Comment by gandaldf** [comment]
Unfortunately no, I'd really like to use SCS in production but I haven't find a way to make it work with Gin.
I'm not really expert about the internals of that router so I hoped you could help me with it.
Wouldn't it be nice if SCS included some adapters for major routers?
Something like you did for DBs but for the middlewares; small packages so anyone can embed just what it need.

**Comment by gandaldf** [comment]
Here there's a Gin middleware that probably worked with an old SCS version:
https://github.com/ms-xy/go-gin-extras/blob/master/middlewares/session/middleware.go
I'm having hard times trying to update it to the new version.
