### ISSUE TITLE
With fiber

### ISSUE THREAD

**Issue by ghost** [alexedwards/scs#143]
Hello

How can I connect scs with Fiber??

**Comment by gandaldf** [comment]
Hi, I PR a Fiber adapter here: #137 
If you can't wait the merge you can use it from my repo: https://github.com/gandaldf/scs I also put an example on how to use it.

**Comment by farfloat** [comment]
@gandaldf 
Hi, thank you for PR and more info about your repo. 
It works!

**Comment by gandaldf** [comment]
Hi @farfloat I'm glad to hear it.
About the CSRF middleware I don't know, I didn't try it; could you try it and report your results here?

**Comment by gandaldf** [comment]
@farfloat have you tried the fiber adpter with the CSRF middleware? Did you have any problems?

**Comment by alexedwards** [comment]
Closing due to lack of response.
