### ISSUE TITLE
Compatibility issues with the Echo framework

### ISSUE THREAD

**Issue by dxvgef** [alexedwards/scs#15]
I use the `scs/session` package in Echo, and if I export anything to the browser in the `HTTPErrorHandler` function of Echo, the Echo of logger will print such warning messages:
`Level:WARN, file:context.go, line:484, message:response, already, committed.`
If I don't use session, there won't be such a problem.

``` Go
package main

import (
	"time"

	"github.com/alexedwards/scs/engine/memstore"
	"github.com/alexedwards/scs/session"
	"github.com/labstack/echo"
)

func main() {
	app := echo.New()
	app.Debug = true
	sessionManager := session.Manage(memstore.New(12 * time.Hour))
	app.Use(echo.WrapMiddleware(sessionManager))
	app.HTTPErrorHandler = errorHandler
	app.Start(":80")
}

func errorHandler(err error, ctx echo.Context) {
	ctx.String(200, "test")
}

```

**Comment by dxvgef** [comment]
I try to remove `manager.go:78` The following code can solve this problem and work fine, do i do not know the hidden dangers?

``` Go
_, err = w.Write(bw.buf.Bytes())
if err != nil {
	m.opts.errorFunc(w, r, err)
}
```

**Comment by alexedwards** [comment]
Again, I'm not too familiar with Echo but I think this was probably being caused by the fact that both SCS and Echo's `HTTPErrorHandler` were trying to call the underlying `http.ResponseWriter.WriteHeader` method.

The new version SCS (> 1.0.0) no longer calls `http.ResponseWriter.WriteHeader` at all so I suspect this is solved.

The code below works for me and triggers a 500 status without any warnings:

```go
package main

import (
	"errors"
	"fmt"

	"github.com/alexedwards/scs"
	"github.com/labstack/echo"
)

var sessionManager = scs.NewCookieManager("u46IpCV9y5Vlur8YvODJEhgOY8m9JVE4")

func main() {
	e := echo.New()
	e.Use(echo.WrapMiddleware(sessionManager.Use))
	e.HTTPErrorHandler = errorHandler

	e.GET("/", func(c echo.Context) error {
		c.Error(errors.New("test"))
		return nil
	})

	e.Start(":4000")
}

func errorHandler(err error, ctx echo.Context) {
	ctx.String(500, fmt.Sprintln(err))
}
```
