### ISSUE TITLE
NATs 

### ISSUE THREAD

**Issue by gedw99** [alexedwards/scs#154]
Nats has a kv Store and is distributed so would be a good store I think.

also very easy to setup and use.

https://docs.nats.io/using-nats/developer/develop_jetstream/kv

anyone else I terraced in this ?

**Comment by alexedwards** [comment]
Sorry, but I don't want to add any more stores to this repository. There's already way too many for me to keep track of --- the only stores I ever personally use are the postgres, mysql and sqlite ones, and it's difficult to effectively maintain stores that I am not familiar with.

I'd be happy for this, or any other stores to be provided in an external repository, and happy to link to them from the main README.
