### ISSUE TITLE
Possible to tag a new version?

### ISSUE THREAD

**Issue by jum** [alexedwards/scs#158]
There have been a few bugs fixed and pull requests merged, but no tag was issued since v2.5.0 more than a year ago. If one wants to get the newest module version, one has to go through some hoops to make that work. Would it be possible to make a v2.5.1 or so?

**Comment by jum** [comment]
For example, I have to use the following replace directives in my go.mod file:

```
replace github.com/alexedwards/scs/v2 => github.com/jum/scs/v2 v2.0.0-20230217205045-4571a76c859e

replace github.com/alexedwards/scs/goredisstore => github.com/jum/scs/goredisstore v0.0.0-20230217205045-4571a76c859e
```

**Comment by alexedwards** [comment]
Done! https://github.com/alexedwards/scs/releases/tag/v2.5.1
