### ISSUE TITLE
Provide a must have session middleware

### ISSUE THREAD

**Issue by bradleyfalzon** [alexedwards/scs#16]
Hi,

Firstly, thank you for this package, I've been rolling my own similar one and in frustration Google again and found this project. This greatly simplifies session management for me, without requiring bring in a library or using an overly simple package like gorilla/sessions (nothing wrong with it, I just needed more).

One piece that I'd also like this to handle is the ability to redirect a user if a session doesn't exist (new user or expired session). For example, keeping sessions for all handlers, except a few that are for logged in users only.

I'm currently handling this with my own middleware successfully. If the user does not have the key username set in the session, they are redirected to `/login`.

```go
func MustExist(next http.Handler) http.Handler {
     return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
         if ok, _ := session.Exists(r, "username"); !ok {
             http.Redirect(w, r, "/login", http.StatusFound)
             return
         }
         next.ServeHTTP(w, r)
     })
 }
```

I'd love to know if there's a way to detect if there's a session at all, as in my case, and the common (but not all) cases, a user would just want to know that someone is logged in.

This isn't a lot of code to write, but it's also possible to get wrong, and I'd want to copy this exact signature across a few sites, so having this provided by the `session` package would be ideal.

To do this, I think it'd be best if it's just a check if the user has a valid session, but the problem I found was that an earlier handler detects the lack of session and added one. So this handler was never able to detect the lack of session. Is there a way to detect if a session doesn't currently exist for this user without adding storing keys?

Would it be possible to provide this middleware as part of the `session` package? I had a stab at an API:

```go
  type MustExist struct {
      Key         string
      RedirectURL string
  }

  func (m *MustExist) Handler(next http.Handler) http.Handler {
      return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
          if ok, _ := session.Exists(r, m.Key); !ok {
              http.Redirect(w, r, m.RedirectURL, http.StatusFound)
              return
          }
          next.ServeHTTP(w, r)
      })
  }
```

And it could be used like:

```go
&MustExist{Key: "username", RedirectURL: "/login"}.Handler
```

But this is still requiring a string key be set, and the API itself is quite ugly. As a user, I'd prefer to just use:

```go
// MustHaveSession redirects a user to redirectURL if no session exists (or it's expired).
// No other handlers or middleware are executed.
func MustHaveSession(redirectURL string) func(http.Handler) http.Handler
```

Is this possible?

**Comment by alexedwards** [comment]
Thanks for the nice feedback and the well explained issue :+1: 

For something as critical as authentication, explicitly checking for the presence of a specific key is the right thing to do. (In fact, you should probably take it further and check your underlying datastore to make sure that the value of the username is still valid too).

Relying on the session being empty as a proxy for a still-valid user being logged sounds dangerous. If another programmer picks up your code in the future and unknowingly uses the session to store some additional data unrelated to the authentication, then there's suddenly a huge security hole in the application.

I can see the convenience of a `MustHaveSession` helper, but from a security point of view it's adding a major footgun to the project.

Your current approach with your own middleware seems right to me (though you should probably handle the error return value from `session.Exists(r, m.Key)`). I use pretty much the same approach in my own projects, if that helps. 

>  Is there a way to detect if a session doesn't currently exist for this user without adding storing keys?

You could check if the length of the array returned by [`session.Keys`](https://godoc.org/github.com/alexedwards/scs/session#Keys) is zero, but the risks above still apply if your using that to determine a user's authentication status.

**Comment by bradleyfalzon** [comment]
> For something as critical as authentication, explicitly checking for the presence of a specific key is the right thing to do.

Makes perfect sense.

> The pre-built MustExist middleware with the explicit key is better, but I think it's assuming too much about what people want to do.

I see your point, I'd think this is a common enough use case to be useful though.

I've tried iterating on a few API designs, where a user could provide a checker function, such as 

```go
  type CheckRedirect struct {
      Check       func(r *http.Request) bool
      RedirectURL string
  }

  func NewCheckRedirect(checker func(*http.Request) bool, redirectURL string) *MustHave {
      return &MustHave{Check: checker, RedirectURL: redirectURL}
  }

  func (m *CheckRedirect) Handler(next http.Handler) http.Handler {
      return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
          if !m.Check(r) {
              http.Redirect(w, r, m.RedirectURL, http.StatusFound)
              return
          }
          next.ServeHTTP(w, r)
      })
  }
```

Where the user could provide it as:

```go
 router.Use(session.CheckRedirect(MustHaveSession, "/login").Handler)

 func MustHaveSession(r *http.Request) bool {
      ok, err := session.Exists(r, "username")
      if err != nil {
          return false 
      }
      return ok
  }
```

The reason I like this is that it's simpler to write tests for and is very explicit. In the end, it would probably be the same amount of lines of code, but those written would be straight forward.

I'm happy to leave things as is, the gain isn't tremendous. If we leave things as is, perhaps an extra section in the docs would be useful for people to just copy/paste and adapt (check different keys and check underlying storage) as required? Such as:

```markdown

### Redirect Middleware

In some cases, you may want to redirect users if the session doesn't have a particular
value (user is not logged in), or if the account associated with the session is no longer enabled.

```go
 // MustBeUser is a middleware that checks if a user is logged in to an enabled
 // account, and redirects to /login if not. Displays an Internal Server Error if the
 // session could not be read successfully.
 func MustBeUser(next http.Handler) http.Handler {
      return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
          // Get the username from session.
          username, err := session.GetString(r, "username")
          if err != nil {
              http.Error(w, "Unable to load session", http.StatusInternalError)
              return
          }

          // Check if user is logged in.
          if username == "" {
              http.Redirect(w, r, "/login", http.StatusFound)
              return
          }

          // Check if user exists in database.
          if !userExistsAndEnabledInDB(username) {
              http.Redirect(w, r, "/login", http.StatusFound)
              return
          }

          // User is logged in to valid account and it's enabled.
          next.ServeHTTP(w, r)
      })
  }
```

**Comment by bradleyfalzon** [comment]
Bump, I'm happy to close this off or make whatever changes you deem appropriate. Completely OK with anything, but I don't want to litter your issues.

**Comment by alexedwards** [comment]
I think you're right -- it's a common enough use-case that having some examples of how to handle authentication is a good idea, and an example like you've suggested would go a long way to making it easier and more obvious how to do it correctly.

I'm working on a v2 of this package at the moment, which is likely to end up having some structural differences to the current version, so l'm happy to leave this open for now and I'll pick this up as part of that.

**Comment by alexedwards** [comment]
I've added a link to a `RequireLogin` middleware example in the main README, which does the same thing as the `MustBeUser` middleware above.
