### ISSUE TITLE
Flush / streaming

### ISSUE THREAD

**Issue by freimer** [alexedwards/scs#186]
It does not appear that this supports streaming, or the ability to flush the writer.  The sessionResponseWriter is not exported (lowercase), so we can't get at the underlying ResponseWriter (w), nor can we call the Unwrap (because we would need to type assert and we can't because sessionResponseWriter is not exported.  So bit of a quandary here, unless I'm just missing something.  Would it be possible to implement http.Flusher?

**Comment by freimer** [comment]
Read #141 and implemented the ResponseController.  Everything works.  I suggest some (prominent) note be added in the docs.  Either it is not there, or I missed it.  Feel free to close this issue, leaving it open so the request to put in docs is noticed...

**Comment by alexedwards** [comment]
Done! https://github.com/alexedwards/scs#flushing-and-streaming-responses

Thanks for the suggestion :+1:
