### ISSUE TITLE
Support multiple sessions per request?

### ISSUE THREAD

**Issue by huangjunwen** [alexedwards/scs#19]
Is it possible to support multiple sessions per request? It seems that now `ContextName` and `CookieName` are global variables.

**Comment by alexedwards** [comment]
Yes, I think it should be possible to support multiple sessions. I'll try to add it when I release the next major version.

**Comment by alexedwards** [comment]
Note to self: multiple session managers will need unique names for their session cookies. I need to add a manager.Name() option, and check that that the name is unique at runtime.

**Comment by alexedwards** [comment]
This is now supported in v1.1.0. When creating multiple session managers, you need to set a unique name for each via the `Name()` method. Usage looks like this:

```go
package main

import (
	"io"
	"net/http"

	"github.com/alexedwards/scs"
)

var sessionManager1 *scs.Manager
var sessionManager2 *scs.Manager

func main() {

	sessionManager1 = scs.NewCookieManager("secret")
	sessionManager1.Name("foo.session")

	sessionManager2 = scs.NewCookieManager("secret")
	sessionManager2.Name("bar.session")

	mux := http.NewServeMux()
	mux.HandleFunc("/put", putHandler)
	mux.HandleFunc("/get", getHandler)

	http.ListenAndServe(":4000", sessionManager1.Use(sessionManager2.Use(mux)))
}

func putHandler(w http.ResponseWriter, r *http.Request) {
	session1 := sessionManager1.Load(r)
	err := session1.PutString(w, "message", "Hello world 1")
	if err != nil {
		http.Error(w, err.Error(), 500)
	}

	session2 := sessionManager2.Load(r)
	err = session2.PutString(w, "message", "Hello world 2")
	if err != nil {
		http.Error(w, err.Error(), 500)
	}
}

func getHandler(w http.ResponseWriter, r *http.Request) {
	session1 := sessionManager1.Load(r)
	message, err := session1.GetString("message")
	if err != nil {
		http.Error(w, err.Error(), 500)
	}
	io.WriteString(w, message)

	session2 := sessionManager2.Load(r)
	message2, err := session2.GetString("message")
	if err != nil {
		http.Error(w, err.Error(), 500)
	}

	io.WriteString(w, message2)
}
```

**Comment by huangjunwen** [comment]
Thank you very much!

**Comment by huangjunwen** [comment]
Suggestion: the context key here should not use a string

```
// at Manager.Use
ctx := context.WithValue(r.Context(), m.opts.name, session)
//                                    ^^^^^^^^^^^^
```

As said in the document of WithValue:

> ...
> // The provided key must be comparable and should not be of type
> // string or any other built-in type to avoid collisions between
> // packages using context.

A non public custom int type can be used instead: assigning each Manager a unique int id as the context key. Also  using int as key maybe a little faster than strings.

**Comment by alexedwards** [comment]
@huangjunwen Thanks for the heads up. I've made the context key an unexported `sessionName` type, which should do the trick of avoiding naming collisions with other packages : https://github.com/alexedwards/scs/commit/254d989ed98c005f3d6537764eee34cfb5a4e74e
