### ISSUE TITLE
Gob register custom struct

### ISSUE THREAD

**Issue by SennaSanzo** [alexedwards/scs#211]
Hi everyone,

I have a question rather than an issue. I have a very simple struct defined as follows:

```go
type User struct {
	ID       uuid.UUID
	Email    string 
	FirstName string
	LastName string
	Password string
	Phone string
	Gender string
	Company string
	IsActive bool
	IsOwner bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
```

When I try to set a session value like this:

```go
sessionManager.Put(r.Context(), "authUser", user)
``` 

where user is a User struct object, I get the error: "gob: type not registered for interface: models.user."

To resolve this, I registered my model at the beginning of my main function using gob.Register(models.User{}), and it works fine.

My question is: is this the correct approach, or am I missing something? I didn't see any mention of this in the README, but I might have overlooked it.

Thanks for your help.

**Comment by jum** [comment]
The SessionManager structure does document that the default codec for session data is encoding/gob, which has that requirement documented. It is customary to perform that registration in an init function where it is declared, not  necessarily the main function. In your case I would place it in the models package.

**Comment by SennaSanzo** [comment]
> The SessionManager structure does document that the default codec for session data is encoding/gob, which has that requirement documented. It is customary to perform that registration in an init function where it is declared, not necessarily the main function. In your case I would place it in the models package.

Thanks for your answer. Like I said I might have overtlooked it and indeed the part of the readme I missed is here: [My bad](https://github.com/alexedwards/scs?tab=readme-ov-file#working-with-session-data)

So I close this thread.
