### ISSUE TITLE
Superfluous WriterHeader Call Warnings

### ISSUE THREAD

**Issue by independentid** [alexedwards/scs#219]
I am getting a lot of these calls which seem to be triggered by calls to SessionManager:

`s.manager.Put(r.Context(), KeyEmail, email)`

`2024-09-13 09:43:56 2024/09/13 16:43:56 http: superfluous response.WriteHeader call from github.com/alexedwards/scs/v2.(*sessionResponseWriter).WriteHeader (session.go:241)`

**Comment by jum** [comment]
I would guess you changed session state after you did already produce output for the page. This is not possible, you have to to do all your changes to the session before you produce any output.

**Comment by independentid** [comment]
I don’t think so. It’s part of a mux filter that executes before the app as part of an oauth2 authorization flow.

When session state changes a redirect occurs (e.g as below).  When a normal app endpoint is reached, the session state is retrieved, if none exists, a redirect starts the login process.

s.manager.Remove(r.Context(), KeyHexaState)
s.manager.Put(r.Context(), KeyEmail, email)
s.manager.Put(r.Context(), KeySubject, sub)
s.manager.Put(r.Context(), KeyIdToken, rawToken)
http.Redirect(w, r, mainPage, http.StatusTemporaryRedirect)
That said, I’m double checking now in case I missed something.

Phil Hunt
***@***.***

**Comment by independentid** [comment]
I found the issue.  It was on my side. Two layers were issuing a redirect to start a login.  Thanks.

**Comment by tsmigiel** [comment]
In case anyone else ends up here like I did:

I had the same message as OP and the error log said I had not registered a type with gob. After registering the type with gob the 'Superfluous ...' message went away.

It would be nice if Put returned an err and I would have discovered the real issue more easily.
