### ISSUE TITLE
The problem of log.Println() in Use() function

### ISSUE THREAD

**Issue by dxvgef** [alexedwards/scs#24]
I use SCS as the session middleware in the Echo framework, but in the process of operating session, if the Redis service is closed, it triggers the log.Println() in the Use() function.
My Code is like this:
`echo.Use(echo.WrapMiddleware(session.Use))`
I hope this error triggers Echo's error and shouldn't print error messages directly on the server console.
How do I do that?

**Comment by srenatus** [comment]
Could you redirect the standard logger to call your (Echo's) log function instead? Similar to how [zap does it](https://github.com/uber-go/zap/blob/f85c78b1dd998214c5f2138155b320a4a43fbe36/global.go#L95-L139)?

Hope this helps 😃

**Comment by jpfluger** [comment]
I'm still getting familiar with scs, but the more I look at it the more I think middleware needs access to getting some private Opts properties, such as `IdleTimeout`. This would allow more middleware to take advantage of scs, including [scs echo middleware](https://github.com/alexedwards/scs/issues/31#issuecomment-360881538).

@srenatus , thanks for the link to [zap](https://github.com/uber-go/zap/). I've been reevaluating loggers lately and this might fit the bill.

**Comment by alexedwards** [comment]
As of commit https://github.com/alexedwards/scs/commit/6f643f463fb7b69725742682bd5f2a10237e2c9a you should now be able to create your own custom middleware instead of using `Use`, and you can have that middleware log (or not) to wherever you want. For example:

```go

var SessionManager = scs.NewCookieManager("u46IpCV9y5Vlur8YvODJEhgOY8m9JVE4")

func MySessionMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		session := SessionManager.Load(r)

		err := session.Touch(w)  // Note: you only need to call this if your idle timeout > 0
		if err != nil {
                        // Log the error to wherever you want
			// Send the user whatever response you want
			return
		}

		ctx := m.AddToContext(r.Context(), session)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```
