### ISSUE TITLE
[discussion] consider switching to bbolt backend

### ISSUE THREAD

**Issue by denisbrodbeck** [alexedwards/scs#25]
Ben Johnson, the creator of [bolt](https://github.com/boltdb/bolt), has declared his project as feature complete and won't provide further support due to lack of time (see [boltdb/bolt@fa5367d](https://github.com/boltdb/bolt/commit/fa5367d20c994db73282594be0146ab221657943)).

CoreOS forked the project over to [bbolt](https://github.com/coreos/bbolt) and pushes development of the project forward. Popular projects based on boltdb, like [storm](https://github.com/asdine/storm) are already on the [migration path](https://github.com/asdine/storm/issues/186) to [bbolt](https://github.com/coreos/bbolt).

Having said that, bolt works great for me, and you've already moved your API to v1, so switching the bolt backend over to bbolt would probably break your v1 contract.

Just opening this issue to raise awareness to the change in bolt's future.

And thanks for this very fine project :smile:

**Comment by alexedwards** [comment]
Thanks for the heads up :-)

I suspect (but am not sure) that the performance of the current bolt back-end implementation could be improved by modeling the data a bit differently anyway, so it would perhaps be a good time to switch if I end up re-writing it anyway.

**Comment by alexedwards** [comment]
Commit https://github.com/alexedwards/scs/commit/53563d4caed1feda18c1914d52101c7290eaf200 fixes this.
