### ISSUE TITLE
Compare to Gorilla Session

### ISSUE THREAD

**Issue by amkgo** [alexedwards/scs#26]
I'm new to Go session management. How does this compare to Gorilla Session?

Thanks,
Andrew

**Comment by jpfluger** [comment]
[gorilla/sessions](https://github.com/gorilla/sessions) is an actively supported repo that has been around a while, having it's first commit way back on [Oct 2, 2012](https://github.com/gorilla/sessions/commit/ea6d91b8bcfd38908e017706751b8ffe1d7da526). For many applications, gorilla/sessions has been great but it has begun to show its age. There's plans for a [gorilla/sessions v2.0](https://github.com/gorilla/sessions/milestone/1).

The past couple days I tested gorilla/sessions and [scs](https://github.com/alexedwards/scs). So far I'm really liking scs over gorilla/sessions for three reasons.

1. I didn't want to fight the gorilla/session's v1 [context bug](https://github.com/gorilla/context) and don't want to wait for a [fix in v2](https://github.com/gorilla/sessions/milestone/1). gorilla/sessions does not use the default Go context package but rather depends on [gorilla/context](https://github.com/gorilla/context). scs uses the native Go context package, which was made part of the standard library in v1.7.0. The newer go context lib doesn't play nice with the older [gorilla/context](http://www.gorillatoolkit.org/pkg/context). An excellent explanation can be found on [StackOverflow](https://stackoverflow.com/questions/43704483/difference-between-golang-standard-context-package-and-gorilla-context-package).
2. gorilla/sessions [updates the sessionid of client-cookies unnecessarily](https://github.com/gorilla/sessions/issues/38). By default, scs does not update the sessionid but still gives me the option to [Renew](https://github.com/alexedwards/scs/blob/876a0fdbdd8ce6c328b2e8064a7483ff377ddaa4/session.go#L654). 
3. I like the scs option of [builtin stores](https://github.com/alexedwards/scs/tree/master/stores). The [store interface](https://github.com/alexedwards/scs/blob/master/store.go) is simple to extend to other data sources.

**Comment by alexedwards** [comment]
@jpfluger Thanks for writing the (accurate and helpful) response 👍
