### ISSUE TITLE
Provide example of using SCS with Echo

### ISSUE THREAD

**Issue by jpfluger** [alexedwards/scs#35]
Should scs include a folder dedicated to middleware examples?  It would be similar to [stores](https://github.com/alexedwards/scs/tree/master/stores) but dedicated to middleware for scs. 

Or would it be better for scs to make reference to third party middleware implementers on its [README](https://github.com/alexedwards/scs)?

It's a classic question. Either direction works for me primarily b/c scs doesn't have many open issues. If scs was highly trafficked in terms of issues, I'd probably suggest breaking-out the middleware to third parties. 

I have some `echo` middleware to contribute - just let me know what you'd prefer.  Others may find a landing spot for their ideas too. (see #16)

**Comment by alexedwards** [comment]
I think that having an example of how to use SCS with Echo would be valuable. 

I'm not keen on adding an examples folder for two reasons: first it clutters the repository with code that isn't core to the project, and secondly if your using a vendoring tool which supports recursive vendoring (like GVT) it could easily lead to dependencies to be installed which aren't actually used in someone's compiled application (see https://github.com/FiloSottile/gvt/issues/84 for an example).

I think a sensible way to address this is for example code to be published as Gists and linked to from the main README. I've just pushed commit https://github.com/alexedwards/scs/commit/2b6a87b9c81e34a20d7e1c8a2be729c67e252566 which adds an examples section and a link to an example.

If you want to add a example of using SCS with Echo, that would be great. I'll update the title of this issue accordingly.

**Comment by jpfluger** [comment]
Works for me. Thanks!

**Comment by jpfluger** [comment]
Oh, but sorry.. my middleware depends on `Opts()` being exposed. Are you okay with merging pull request #33?

**Comment by alexedwards** [comment]
It looks like Echo now provides it's own official session middleware which works with the Echo `Request` and `Response` objects. I think that this would be a better fit for users of Echo instead of trying to shoehorn SCS into their application.

I've updated the README in https://github.com/alexedwards/scs/commit/4c090493e5b46a70a067bf2c2eec26d8f48cc863

**Comment by danielbprice** [comment]
@alexedwards Just to push back lightly-- AFAICT, what echo has done is a thin wrapper for gorilla/sessions.

I compared the pgstore backend available for gorilla/sessions to the one you wrote for scs, and by far, I prefer your approach.  The table is simpler, it isn't auto-created, it is properly indexed, and the code is easier to audit and reason about.

So now I'm vexed-- I'd rather use scs, but I don't really want to drop echo, either.  @jpfluger is your middleware usable with scs as it now stands?

**Comment by jpfluger** [comment]
@danielbprice Yes, it should be usable. But it's also 6 commits behind with this repo and different than my local version which I use extensively in my projects. I need to clean that up and might re-fork to save time (you've been warned! :). @alexedwards does a great job maintaining scs so I would prefer to re-integrate with his repo. I'll make time on Sunday to work on this.

**Comment by spazzymoto** [comment]
Sorry to raise a dead issue, but i created [Echo SCS Session](https://github.com/spazzymoto/echo-scs-session ) if anyone is interested in using scs with echo

**Comment by alexedwards** [comment]
@spazzymoto Thanks, I've added a link to echo-scs-session in the SCS README :+1:

**Comment by jpfluger** [comment]
@spazzymoto Very elegant solution using Echo with SCS. Highly recommended for echo users to check-out [Echo SCS Session](https://github.com/spazzymoto/echo-scs-session) and adapt to suit your own Echo projects. :1st_place_medal:
