### ISSUE TITLE
Using scs with Negroni

### ISSUE THREAD

**Issue by socceroos** [alexedwards/scs#4]
Due to the nature of the middleware returned from session.Manage(), I'm not seeing a way to chain this middleware with Negroni.

Is there a way to use the middleware provided by scs within negroni?

**Comment by alexedwards** [comment]
I've not used Negroni myself, and although I've had a quick look at the source code I'm not confident what the right fix is.

Would changing the `Manage` function to directly return a `func(http.Handler) http.Handler` instead of the `Middleware` type be sufficient for this to work with Negroni?

**Comment by alexedwards** [comment]
The simplest way to use it with Negroni seems to be to wrap either your mux (within `negroni.UseHandler`) or the `negroni.Negroni` instance with the SCS middleware, as both are just http.Handlers.

For example, wrapping your mux:

```go
engine := memstore.New(0)
sessionManager := session.Manage(engine)

mux := http.NewServeMux()
mux.HandleFunc("/", indexHandler)

n := negroni.Classic()
n.UseHandler(sessionManager(mux))
http.ListenAndServe(":3000", n)
``

Or wrapping the whole Negroni instance:

```go
engine := memstore.New(0)
sessionManager := session.Manage(engine)

mux := http.NewServeMux()
mux.HandleFunc("/", indexHandler)

n := negroni.Classic()
n.UseHandler(mux)
http.ListenAndServe(":3000", sessionManager(n))
```

Generally speaking, I can't see a way to use middleware with the signature `func(http.Handler) http.Handler` (like SCS) with Negroni. It's odd that it doesn't appear to support it at all, given that it's pretty much the standard signature for Go middleware.  

The [Negroni third-party middleware](https://github.com/urfave/negroni#third-party-middleware) I've looked at seems to be either Negroni-specific or implements a special constructor just for Negroni. The latter approach could be an option for SCS, but I'd probably prefer not to introduce it when it feels like quite a special-case and there's a workable and reasonable alternative (i.e the snippets above).
