### ISSUE TITLE
[help] Strange behavior

### ISSUE THREAD

**Issue by gstvg** [alexedwards/scs#48]
Sorry, i cant share the code right now. Just need some light for finding the issue. Sometimes the session just doesnt work and create many tokens for the same user (im using mysqlstore, so is easy to see this). Now session only works after calling RenewToken. Did this descriptions identify with any common misuse of the library? Ive already tried a lot of things. Thanks and sorry for the lack of more info.

**Comment by alexedwards** [comment]
It could be something to do with your cookies not being sent back by your browser... Are the cookie path, domain, httponly and secure settings are correct?

**Comment by gstvg** [comment]
Hi, thanks. Accessing from localhost with no custom setting should work right?
Ive used even Wireshark to confirm, browser send the cookie and receives a new Set-Cookie header, without calling RenewToken. Thanks again!

**Comment by alexedwards** [comment]
Yes, it should work from localhost with not custom settings. Are you using a framework or just plain net/http?

**Comment by gstvg** [comment]
Thank you. Misconfigured database time make every token expired as soon as created. Sorry, my bad. And thanks for the awesome library.
