### ISSUE TITLE
get notified when a session expires by its life time

### ISSUE THREAD

**Issue by blueturtle13g** [alexedwards/scs#53]
how can I get notified when a session expires by its lifetime?
I need it because I want to set the user state as offline. when he or she logs out or it's session lifetime expires.
thanks.

**Comment by alexedwards** [comment]
Hi,

What backend are you using? Cookies, Redis, Postgres etc?

Also, are you using the `IdleTimeout()` setting?

**Comment by alexedwards** [comment]
With v2.0.0 this should now be possible. The [`Commit()`](https://godoc.org/github.com/alexedwards/scs#Session.Commit) method returns the session token and expiry time after saving the session data to the store. You can use middleware to automate saving the session data and do whatever else you need to do with the expiry time, similar to this gist: https://gist.github.com/alexedwards/cc6190195acfa466bf27f05aa5023f50
