### ISSUE TITLE
[discussion] consider cookieless sessons

### ISSUE THREAD

**Issue by ChristophPech** [alexedwards/scs#54]
For an API I needed to store the session-id somewhere else instead of the cookie header field. So I added the possibility to also use a string instead of an http.Request. Sadly it breaks the public API so I won't issue a pull request, but maybe someone else has a better idea making it work without breaking changes.

https://github.com/ChristophPech/scs

**Comment by alexedwards** [comment]
@ChristophPech I'm working on a v2 release at the moment and would like to address this issue if possible. A couple of questions (if you can remember!)...

What was the motivation behind this? Was it because you wanted to communicate the session ID to/from the user in a different HTTP header field? Or were you wanting to use sessions completely outside of the context of a web application and HTTP request-response cycle?

**Comment by ChristophPech** [comment]
I am putting the session cookie into a field in a JSON as well as XML API. Yes, I use mostly HTTP for now but I'd like to stay protocol agnostic as I have different protocol clients for different game engines and different platforms. All data of the protocol is inside the payload so it will be easy to use different transmission channels other than HTTP. For example, a loadbalancing server could collect multiple client requests and send them in bulk to the application server. Additionally messing with cookies on several different client http libraries can be a bit difficult.

The only advantage to use http cookies is that a webbrowser will save, send and expire them automatically. But once the client is not a webbrowser there are only disadvantages left.

**Comment by alexedwards** [comment]
In the v2.0.0 release loading and saving of the session data is decoupled from the process of communicating the session token to/from the client, so cookieless sessions are now much easier to implement.

For convenience, I've included a `LoadAndSave()` middleware in the package which reads/writes the token to a cookie. But you can use this a template to implement your own middleware which reads/writes the token to an alternative location, like a HTTP header. Here's an example gist: https://gist.github.com/alexedwards/cc6190195acfa466bf27f05aa5023f50

**Comment by ChristophPech** [comment]
Awesome. Thanks.
