### ISSUE TITLE
go get github.com/alexedwards/scs/v2 fails

### ISSUE THREAD

**Issue by krsanky** [alexedwards/scs#59]
go get github.com/alexedwards/scs/v2
package github.com/alexedwards/scs/v2: cannot find package "github.com/alexedwards/scs/v2" in any of:
        /usr/local/go/src/github.com/alexedwards/scs/v2 (from $GOROOT)
        /home/wise/go/src/github.com/alexedwards/scs/v2 (from $GOPATH)

I'm moving a site I have in development to a new machine.  I have the site working on another machine, I last set that one up maybe a week ago.  

What's the easiest way to use scs and postgresql?

**Comment by alexedwards** [comment]
Are you using modules for the dependencies in your project, or the traditional GOPATH approach?

**Comment by alexedwards** [comment]
For running it under your `GOPATH`:

* Install without the `v2` postfix:  `go get github.com/alexedwards/scs`
* Import without the `v2` postfix:  `import "github.com/alexedwards/scs"`

Everything else should work as normal as documented after that.

But yes, I definitely recommend switching to using modules. There's a great introduction [here](https://github.com/golang/go/wiki/Modules).

**Comment by alexedwards** [comment]
I'll update the installation instructions in the README to make this clearer.

**Comment by krsanky** [comment]
Thanks for the help.

**Comment by krsanky** [comment]
For posterity:
My underlying issue was that the scs api had simply changed in between me working on it.
I needed to update my code from the Manager.Load interface to using the simpler Session one. 
Ironically this is something that the go modules approach would mitigate going forward, because you are more deliberate about versions when importing go code.
thanks again

**Comment by alexedwards** [comment]
Thanks for the explanation and sorry for any trouble. It sounds like it was just unfortunate timing! The API should be stable now for a long time, and you're right, modules will address exact this problem in the future anyway.
