### ISSUE TITLE
Get compile error undefined: http.SameSite

### ISSUE THREAD

**Issue by jayeshnachnani** [alexedwards/scs#60]
I am new to golang, using go1.10 and trying to compile

I get undefined: http.SameSite  error during compiliation

Stackoverflow seems to suggest that it is because of go version, although this is unconfirmed

https://stackoverflow.com/questions/55895541/encountered-an-error-samesite-http-samesitelaxmode

**Comment by alexedwards** [comment]
Yes, it requires Go 1.11 (see https://github.com/alexedwards/scs#compatibility).

This is because it sets the `SameSite` attribute on the session cookie for additional security, but that attribute is only supported in 1.11 onwards.

I'll update the readme to make this clearer right at the top.

**Comment by jayeshnachnani** [comment]
thanks a lot for the quickest response possible!

Yes I read up the below link as well, the SameSite attribute itself is newish and therefore newish in Go!

https://medium.com/compass-security/samesite-cookie-attribute-33b3bfeaeb95
