### ISSUE TITLE
Using Session to represent Session Manager is prone to ambiguity on v2

### ISSUE THREAD

**Issue by Delphier** [alexedwards/scs#61]
Session usually represents a single session.
Is Sessions or SessionManager better?

**Comment by alexedwards** [comment]
I think I agree.

When I was creating `v2`, my logic was that almost all the methods act on a single session. For example `Put()` adds data to the session for the current user, and `LoadAndSave()` loads and saves the session for the current user. I think the naming makes sense in those contexts.

```gi
session.Put(r.Context(), "message", "Hello from a session!")
```

But you're right, the naming feels a bit wrong for the setup stage, where you are configuring settings for all sessions:

```go
session = scs.NewSession()
session.Lifetime = 24 * time.Hour
```

If we change the name from `Session` to `Sessions`, then I think the ambiguity problem still exists -- it is just reversed. 

`SessionManager` is probably a better name and works OK for both aspects.

The `scs.NewSession()` function would also need to be renamed to `scs.NewSessionManager()` --- or perhaps just `scs.New()`.

I don't want to make any breaking changes to the repository at this moment though. But I think it might be possible to achieve without breaking the API by type aliasing `type Sessions = SessionManager`, and marking `scs.NewSession()` and deprecated in the comments.

**Comment by Delphier** [comment]
@alexedwards This is a good solution.

**Comment by alexedwards** [comment]
I've now implemeted this in commit 1e47e13c2422357f96997d3c6fd239e8fcd222d5 : )
