### ISSUE TITLE
Getting token value in v2

### ISSUE THREAD

**Issue by szqmtl** [alexedwards/scs#62]
Congratulations on v2.

Would you consider adding a function similar to Token() in v1 for fetching the token value? I have a problem to keep track on the latest login by session token because I cannot get the value after calling RenewToken. Maybe is there an alternative way?

it'd work for me in my case If adding this function in data.go, but only a thought. 
```go
func (s *Session) Token(ctx context.Context) string {
	sd := s.getSessionDataFromContext(ctx)
	return sd.token
}
```

Thanks for the library.

**Comment by alexedwards** [comment]
Thanks!

You can can call the [`Commit()`](https://godoc.org/github.com/alexedwards/scs#Session.Commit) method after `RenewToken()`, and that will return the new session token (and expiry time).

**Comment by szqmtl** [comment]
is there any side effect if I call `Commit()` multiple times?

**Comment by alexedwards** [comment]
From a data-integrity point of view it is fine to call `Commit()` multiple times. And it's also OK to use in addition to the `LoadAndSave()` middleware. The only side-effects are:

1. You're making an additional database query with each call to `Commit()`.
2. If you're using `IdleTimeout`, the timeout will begin from the *last* call to `Commit()` that is made.

But yes, in general there should be no problem with doing that.

**Comment by szqmtl** [comment]
thanks a lot.
