### ISSUE TITLE
how to set IdleTimeout "Session"

### ISSUE THREAD

**Issue by buffge** [alexedwards/scs#63]
IdleTimeout field is time type
l want set session name cookie's expires "Session"

**Comment by alexedwards** [comment]
Sorry, I don't understand this.

Can you reword the question and provide more detail?

Thanks : )

**Comment by buffge** [comment]
l want set cookie's expires "Session" , Instead of Actual time
![123](https://user-images.githubusercontent.com/24917906/60446514-15e49a80-9c54-11e9-8aa8-f1953e2e2cd8.jpg)
I tried to set IdleTimeout to 0 and not setup. but don't effect

**Comment by alexedwards** [comment]
Try setting `Persist = false`:

```
sessionManager = scs.New()
sessionManager.Cookie.Persist = false
```

That will mean that no `Expires/Max-Age` value is set on the cookie and it will be removed at the end of the user's 'session' when they close their browser.

**Comment by buffge** [comment]
I apologize for my carelessness!
Thanks
