### ISSUE TITLE
scs: no session data in context

### ISSUE THREAD

**Issue by ThomasJunk** [alexedwards/scs#64]
Abstract: Example code not working - resulting in stacktrace

[Example used](https://gist.github.com/ThomasJunk/72fcbef72611279db9ba9b8335d0487b)

At first, I suspected some issues with the filesystem (though `/tmp` should be writable). 
But even if you substitute the `bolt` examplecode by the `memstore` example code, the app crashes.

Operating system: 
`Linux MYBOX 5.1.16-1-default #1 SMP Wed Jul 3 12:37:47 UTC 2019 (2af8a22) x86_64 x86_64 x86_64 GNU/Linux`

Go Version: `go version go1.12.6 linux/amd64`

**Comment by alexedwards** [comment]
You need to wrap the mux (or the handler) with the [LoadAndSave()](https://godoc.org/github.com/alexedwards/scs#SessionManager.LoadAndSave) middleware.

There's a basic example here: https://github.com/alexedwards/scs#basic-use

**Comment by ThomasJunk** [comment]
Oh, sorry for bothering you. 😳 
Stupid me!! Typical beginner mistake.
Thanks for taking the time!

**Comment by alexedwards** [comment]
No worries. Hope it's smooth sailing from here :-)

**Comment by Koredeoluwafemi** [comment]
I am having this issue on the go fiber framework, how and where do I pass in the http.handler into the LoadAndSave middleware
