### ISSUE TITLE
Deploying to Appengine Without Modules

### ISSUE THREAD

**Issue by bonesyo** [alexedwards/scs#76]
There is an error when deploying to appengine without using modules.

```
failed analyzing /home/james/hello-world: cannot find package "github.com/alexedwards/scs/v2/memstore"
```

I went into your package and changed `"github.com/alexedwards/scs/v2/memstore"` to `"github.com/alexedwards/scs/memstore"` in the `session.go` file and it now works.

**Comment by alexedwards** [comment]
I'm not clear about what, if anything needs to happen here. As far as I can see `"github.com/alexedwards/scs/v2/memstore"` is the correct import path for the v2 memstore implementation and I can't replicate the issue. Perhaps it was some kind of caching issue?

I'm going to close this, but if it is still a problem please reopen.
