### ISSUE TITLE
Anyone successfully use this with github.com/go-chi/chi?

### ISSUE THREAD

**Issue by jherman** [alexedwards/scs#83]
Hi all,

Been attempting to use this with chi, but haven't had any luck.  Works well when I remove chi from the equation, but seems to throw a `scs: no session data in context` exception otherwise.

Any advice?

**Comment by alexedwards** [comment]
Yes, I've never had a problem using it with chi. 

Can you post a minimum reproducible example or test case please?

**Comment by PatWie** [comment]
I can second that. No issues with chi and scs:
https://github.com/infomark-org/infomark/blob/e45ed2dff4504b80d7d789e109affbfb70aac206/auth/authenticate/authenticator.go#L39

**Comment by jherman** [comment]
I was able to get it to work. Thanks folks for helping confirming it does work.
