### ISSUE TITLE
SessionManager scope

### ISSUE THREAD

**Issue by sachinwalia2k8** [alexedwards/scs#9]
Can you please tell if SessionManager is global in scope meaning bootstrapped from some Init function

**Comment by alexedwards** [comment]
There's no global init function.

The `manager` middleware is scoped to wherever you instansiate it via the `session.Manage` function.

**Comment by sachinwalia2k8** [comment]
Thanks, what I wanted to also check is that if SessionManager is thread-safe such that if I define it in global scope in main file and access this global scoped SessionManager from multiple http handlers then is this an acceptable model?

**Comment by alexedwards** [comment]
The short answer is it's safe. The session management middleware doesn't access any shared state, it only modifies things within the scope of the current goroutine handling the request.

But what do you mean by 'access' it? It's middleware -- so 'access' is an unusual choice of word. Can  you give me an example of what you mean?

**Comment by sachinwalia2k8** [comment]
Hi @alexedwards thanks for explanation. I came from Java world so may be I am trying to apply the dependency injection idea here. I was using Gorilla Sessions earlier and there is a notion of session store which can be initialized like below. I've looked at your code and realized that session here is a middleware that you wrap over your handlers. I guess that possibly was cause of confusion.

Something like below may give you an idea what I meant by global. After these init functions are called you can access for example DBConn as config.DBConn to get actual connections etc...

```
package config

import (
//necessary imports
)

var DBConn *sqlx.DB
var RedisPool *redis.Pool
var RedisSessionStore *redistore.RediStore //Gorilla session store backed by Redis.


func InitDB(){
//DB init
}

func InitRedis(){
//Redis pool init
}

func InitSessionStore(){
//session store init code
}


```

**Comment by alexedwards** [comment]
No problem, I see what you mean now.

Yes, there's nothing concurrency-unsafe about the middleware itself.

You do need to make sure that any engine that you're using to persist the session data is concurrency-safe. If you're using any of the [offical engines](https://github.com/alexedwards/scs#installation) then the these are concurrency-safe and there's nothing to worry about.
