### ISSUE TITLE
Support fasthttp?

### ISSUE THREAD

**Issue by futureday2015** [alexedwards/scs#91]
I am wondering if this session management lib supports fasthttp. Thanks

**Comment by alexedwards** [comment]
No, sorry. It is designed to be compatible with Go's net/http package.

**Comment by futureday2015** [comment]
@alexedwards  any technical reasons why don't intend to support fasthttp? thanks a lot.

**Comment by alexedwards** [comment]
Just to check, you're talking about https://github.com/valyala/fasthttp right?

**Comment by futureday2015** [comment]
@alexedwards yes. thanks.
